name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Update if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Add macOS platform to bundler (to resolve rb-fsevent issue)
        run: bundle lock --add-platform x86_64-darwin

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set path vendor/bundle
          bundle config set without 'darwin'
          bundle install --jobs 4 --retry 3

      - name: Build the Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
